$(document).ready(function(){
    $('#design').click(function(){
        $('#design').toggle(2000);
        $('.design-text').toggle(2000);
    });
    $('.design-text').click(function(){
        $('#design').toggle(2000);
        $('.design-text').toggle(2000);
    });
});
$(document).ready(function(){
    $('#development').click(function(){
        $('#development').toggle(2000);
        $('.development-text').toggle(2000);
    });
    $('.development-text').click(function(){
        $('#development').toggle(2000);
        $('.development-text').toggle(2000);
    });
});
$(document).ready(function(){
    $('#product').click(function(){
        $('#product').toggle(2000);
        $('.product-text').toggle(2000);
    });
    $('.product-text').click(function(){
        $('#product').toggle(2000);
        $('.product-text').toggle(2000);
    });
});

